"""change culmn

Revision ID: 147dfaa015a3
Revises: d79b6904d6e9
Create Date: 2026-08-02 15:15:59.203566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147dfaa015a3'
down_revision: Union[str, Sequence[str], None] = 'd79b6904d6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('country', sa.String(length=100), nullable=True))
    op.drop_column('places', 'countries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('countries', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('places', 'country')
    # ### end Alembic commands ###
