name: Build and Deploy Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build and Deploy Application Stack
        run: docker compose up -d --build
