name: Build and Deploy Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Images
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Frontend and Backend Images
        run: docker compose build

  deploy:
    name: Deploy Application Stack
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Deploy Database, Backend, Frontend
        run: docker compose up -d
